[package]
name = "minhash"
version = "0.0.1"
edition = "2018"
authors = ["Stefan Grafberger <s.grafberger@uva.nl>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
